# SPDX-FileCopyrightText: 2024 Jonas Fierlings <fnoegip@gmail.com>
#
# SPDX-License-Identifier: 0BSD
---
name: Lint Repository

on:
  push:
    branches:
      - main

  pull_request:

  merge_group:

  workflow_dispatch:

permissions:
  contents: read # for actions/checkout

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Lint-Repository:
    runs-on: ubuntu-24.04
    if: github.event.pull_request.draft != true
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Check REUSE compliance
        uses: fsfe/reuse-action@676e2d560c9a403aa252096d99fcab3e1132b0f5 # v6.0.0
      - name: Install editorconfig-checker
        uses: editorconfig-checker/action-editorconfig-checker@0ab3427a3f09b17c21d489172245be511e0a16ea # v2.0.0
      - name: Check EditorConfig compliance
        run: editorconfig-checker
